# Generated by Django 4.1.11 on 2023-09-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('property_cost', models.CharField(max_length=50)),
                ('property_type', models.CharField(max_length=100)),
                ('property_area', models.CharField(max_length=100)),
                ('property_locality', models.CharField(max_length=200)),
                ('property_city', models.CharField(max_length=100)),
                ('individual_property_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
