# Generated by Django 4.1.11 on 2023-09-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0002_property_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('successful_records', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('trigger_timing', models.CharField(max_length=100)),
            ],
        ),
    ]
